#ifndef BLOK_MODEL_COMPASS_H
#define BLOK_MODEL_COMPASS_H

enum TCompass {
    BLOK_DIRECTION_NORTH = 12,
    BLOK_DIRECTION_EAST = 3,
    BLOK_DIRECTION_SOUTH = 6,
    BLOK_DIRECTION_WEST = 9
};

#endif