#ifndef BLOK_ERROR_H
#define BLOK_ERROR_H

#define BLOK_OPERATION_SUCCESS 0
#define BLOK_NULL_POINTER_ERROR (-1)

#define BLOK_VECTOR_NULL (-31801)
#define BLOK_VECTOR_ARRAY_NULL (-31802)
#define BLOK_VECTOR_REALLOC_FAILED (-31803)
#define BLOK_VECTOR_CAPACITY_FULL (-31804)
#define BLOK_VECTOR_INVALID_SIZE (-31805)

#define BLOK_WINDOW_REGISTRATION_ERROR 0
#define BLOK_WINDOW_CREATION_ERROR (-32902)

#endif