#ifndef BLOK_MACROS_H
#define BLOK_MACROS_H

#define BLOK_MAX_CHAR_LENGTH 260

#define BLOK_EXIT_IF(CONDITION) \
    if (CONDITION) return

#define BLOK_NON_VOID_EXIT_IF(CONDITION, RETURN_VALUE) \
    if (CONDITION) return (RETURN_VALUE)

#define BLOK_FREE_IF_NOT_NULL(OBJECT, FUNC) \
    if ((OBJECT) != NULL) FUNC(OBJECT)

#define BLOK_SUCCESSFUL_OPERATION 0

#define BLOK_ERROR_NULL_POINTER (-1)

#define BLOK_ERROR_WINDOW_CREATION (-28)

#define BLOK_ERROR_WINDOW_REGISTRATION 0


#endif