#ifndef BLOK_MACROS_H
#define BLOK_MACROS_H

#define BLOK_MAX_CHAR_LENGTH 260

#define BLOK_EXIT_IF(CONDITION) \
    if (CONDITION) return

#define BLOK_NON_VOID_EXIT_IF(CONDITION, RETURN_VALUE) \
    if (CONDITION) return (RETURN_VALUE)

#define BLOK_FREE_IF_NOT_NULL(OBJECT, FUNC) \
    if ((OBJECT) != NULL) FUNC(OBJECT)


#endif