#ifndef BLOK_MACROS_H
#define BLOK_MACROS_H

#define BLOK_MAX_CHAR_LENGTH 260

#define BLOK_EXIT_IF(CONDITION) \
    if (CONDITION) return

#define BLOK_NON_VOID_EXIT_IF(CONDITION, RETURN_VALUE) \
    if (CONDITION) return (RETURN_VALUE)

#define BLOK_FREE_IF_NOT_NULL(OBJECT, FUNC) \
    if ((OBJECT) != NULL) FUNC(OBJECT)

#define BLOK_SUCCESSFUL_OPERATION 0

#define BLOK_ERROR_NULL_POINTER (-1)

#define BLOK_ERROR_WINDOW_CREATION (-28)

#define BLOK_ERROR_WINDOW_REGISTRATION 0

#define BLOK_ERROR_VECTOR_ARRAY_NULL (-210)

#define BLOK_ERROR_VECTOR_NO_INDEX_AVAILABLE (-324)

#define BLOK_ERROR_VECTOR_INDEX_NOT_FOUND (-342)

#define BLOK_ERROR_VECTOR_OUT_OF_RANGE (-232)

#define BLOK_VECTOR_FULL (-3204)

#define BLOK_VECTOR_NOT_FULL (-32432)

#define BLOK_VECTOR_EMPTY (-3242)

#define BLOK_VECTOR_NOT_EMPTY (-324230)

#endif